
package view;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import persistencia.DAO;
import model.Produtos;
import controle.ConProdutos;

import java.awt.event.*;
import java.awt.Font;

/**
 *
 * @author RicardoNote
 */
public class CadastroProdutos extends javax.swing.JPanel {

	/**
	 * Creates new form CadastroProdutos
	 */
	public CadastroProdutos() {
		initComponents();
		

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		txtCodigoBarras = new javax.swing.JTextField();
		txtCodigoBarras.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent ev) {
				String caracteres = "0987654321"; // ESTE EVENTO VAI RESTRIGIR A
													// ENTRADA DE CARACTERES

				if (!caracteres.contains(ev.getKeyChar() + "")) {

					ev.consume();

				}

			}
		});
		txtValidade = new javax.swing.JTextField();
		txtFabricacao = new javax.swing.JTextField();
		txtLote = new javax.swing.JTextField();
		txtDescricao = new javax.swing.JTextField();
		txtAplicacao = new javax.swing.JTextField();
		txtMedida = new javax.swing.JTextField();
		txtMedida.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent ev) {
				String caracteres = "0987654321"; // ESSE EVENTO VAI RESTRIGIR A
													// ENTRADA DE NUMEROS

				if (caracteres.contains(ev.getKeyChar() + "")) {

					ev.consume();

				}
			}
		});
		btnIncluir = new javax.swing.JButton();
		btnSalvar = new javax.swing.JButton();
		btnExcluir = new javax.swing.JButton();
		btnPesquisar = new javax.swing.JButton();
		btnAlterar = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		tblTabela = new javax.swing.JTable();
		btnSair = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel2.setText("Descrição");

		jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel3.setText("Código de Barras");

		jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel4.setText("Medida");

		jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel5.setText("Validade");

		jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel6.setText("Fabricação");

		jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel7.setText("Lote");

		jLabel8.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
		jLabel8.setText("Aplicação");

		btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/add.png"))); // NOI18N
		btnIncluir.setToolTipText("Incluir");
		btnIncluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIncluirActionPerformed(evt);
			}
		});

		btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/Botoes_5103_usb_48.png"))); // NOI18N
		btnSalvar.setToolTipText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/Botoes_5116_cross_48.png"))); // NOI18N
		btnExcluir.setToolTipText("Excluir");
		btnExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExcluirActionPerformed(evt);
			}
		});

		btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/Lupas_1330_21.jpg"))); // NOI18N
		btnPesquisar.setToolTipText("Pesquisar");
		btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPesquisarActionPerformed(evt);
			}
		});

		btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/alterar.png"))); // NOI18N
		btnAlterar.setToolTipText("Alterar");
		btnAlterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAlterarActionPerformed(evt);
			}
		});

		tblTabela.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(tblTabela);

		btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/domesticos_2141_porta.gif"))); // NOI18N
		btnSair.setToolTipText("Sair");
		btnSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSairActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jScrollPane2)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addComponent(
																																txtCodigoBarras,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																136,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGap(139,
																																139,
																																139)
																														.addComponent(
																																jLabel4)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																														.addComponent(
																																txtMedida,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																99,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addComponent(
																												txtDescricao,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												457,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								txtAplicacao,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								457,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGap(72,
																																				72,
																																				72)
																																		.addComponent(
																																				btnExcluir,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				72,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(26,
																																				26,
																																				26)
																																		.addComponent(
																																				btnPesquisar,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				70,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(26,
																																				26,
																																				26)
																																		.addComponent(
																																				btnSalvar,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				76,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				txtValidade,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				92,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel6)
																																		.addGap(18,
																																				18,
																																				18)
																																		.addComponent(
																																				txtFabricacao,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				108,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel7)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																txtLote)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGap(10,
																																				10,
																																				10)
																																		.addComponent(
																																				btnSair,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				71,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(0,
																																				0,
																																				Short.MAX_VALUE))))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				btnIncluir,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				71,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				btnAlterar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				71,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(21, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(14, 14, 14)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																txtCodigoBarras,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																txtMedida,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																txtDescricao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																txtAplicacao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																txtValidade,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																txtFabricacao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txtLote,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																btnExcluir)
														.addComponent(
																btnPesquisar)
														.addComponent(
																btnAlterar)
														.addComponent(
																btnIncluir,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnSalvar,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btnSair,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(24, 24, 24)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												251,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(102, 102, 255));
		jLabel1.setText("Formulario de Cadastro de FrmProdutos");
		jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(163,
																		163,
																		163)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jPanel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addGap(16, 16, 16)));
	}// </editor-fold>

	
	private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
		Produtos produtos = new Produtos();
		String descricao = txtDescricao.getText();
		txtDescricao.setText(txtDescricao.getText().toUpperCase());
		txtAplicacao.setText(txtAplicacao.getText().toUpperCase());
		txtMedida.setText(txtMedida.getText().toUpperCase());
		
		if (descricao != ("")) {		//Validação da descrição
		 produtos.setDescricao(descricao);
		 } else {
		 JOptionPane.showMessageDialog(null,
		 "O campo Descrição e obrigatório");
		 }
		
	//	if ()
	}

	private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAlterar;
	private javax.swing.JButton btnExcluir;
	private javax.swing.JButton btnIncluir;
	private javax.swing.JButton btnPesquisar;
	private javax.swing.JButton btnSair;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable tblTabela;
	private javax.swing.JTextField txtAplicacao;
	private javax.swing.JTextField txtCodigoBarras;
	private javax.swing.JTextField txtDescricao;
	private javax.swing.JTextField txtFabricacao;
	private javax.swing.JTextField txtLote;
	private javax.swing.JTextField txtMedida;
	private javax.swing.JTextField txtValidade;
	// End of variables declaration
}
