/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Window.Type;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author RicardoNote
 */
// Homologado por : Vinicius Menezes
public class FrmVendas extends javax.swing.JFrame {

    /**
     * Creates new form FrmVendas
     */
    public FrmVendas() {
    	
    	setIconImage(Toolkit.getDefaultToolkit().getImage(FrmVendas.class.getResource("/images/th.jpg")));
    	setResizable(false);
    	setTitle("VENDAS");
    	setType(Type.UTILITY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCodigoProduto = new javax.swing.JLabel();
        lbCodigoBarras = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbAplicacao = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtAplicacao = new javax.swing.JTextField();
        lbImagem = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnPesquisar.setIcon(new ImageIcon(FrmVendas.class.getResource("/images/zoom.png")));
        tabelaPesquisaProdutos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbItens = new javax.swing.JLabel();
        btnLimpa = new javax.swing.JButton();
        btnLimpa.setIcon(new ImageIcon(FrmVendas.class.getResource("/images/cancel.png")));
        btnFinaliza = new javax.swing.JButton();
        btnFinaliza.setIcon(new ImageIcon(FrmVendas.class.getResource("/images/money_dollar.png")));
        btnFechar = new javax.swing.JButton();
        btnFechar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		dispose();
        	}
        });
        btnFechar.setIcon(new ImageIcon(FrmVendas.class.getResource("/images/door_out.png")));
        lbSubTotal = new javax.swing.JLabel();
        tabelaProdutos = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbCodigoProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCodigoProduto.setText("Codigo Produto");

        lbCodigoBarras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCodigoBarras.setText("Código Barras");

        lbDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDescricao.setText("Descrição");

        lbAplicacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbAplicacao.setText("Aplicação");

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/th.jpg"))); // NOI18N

        btnPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(lbCodigoProduto)
        					.addGap(18)
        					.addComponent(txtCodigoProduto, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        					.addGap(35)
        					.addComponent(lbCodigoBarras)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(txtCodigoBarras, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lbDescricao)
        						.addComponent(lbAplicacao))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtDescricao)
        						.addComponent(txtAplicacao))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnPesquisar)
        			.addGap(22)
        			.addComponent(lbImagem)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lbCodigoProduto)
        						.addComponent(lbCodigoBarras)
        						.addComponent(txtCodigoBarras, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtCodigoProduto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(24)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lbDescricao)
        						.addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lbAplicacao)
        						.addComponent(txtAplicacao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnPesquisar)))
        				.addComponent(lbImagem, GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPesquisaProdutos.setViewportView(jTable1);

        lbItens.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbItens.setForeground(new java.awt.Color(51, 51, 255));
        lbItens.setText("Itens");

        btnLimpa.setText("Limpa F6");

        btnFinaliza.setText("Finaliza F5");

        btnFechar.setText("Fechar F4");

        lbSubTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbSubTotal.setForeground(new java.awt.Color(51, 51, 255));
        lbSubTotal.setText("SubTotal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lbItens)
        				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        					.addComponent(btnLimpa)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btnFinaliza)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnFechar))
        				.addComponent(lbSubTotal))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(41)
        			.addComponent(lbItens)
        			.addGap(18)
        			.addComponent(lbSubTotal)
        			.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnFechar)
        				.addComponent(btnFinaliza)
        				.addComponent(btnLimpa))
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaProdutos.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(tabelaProdutos, GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addComponent(tabelaPesquisaProdutos, GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tabelaPesquisaProdutos, GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(tabelaProdutos, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(3))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FrmVendas vendas = new FrmVendas();
               vendas.setVisible(true);
               vendas.setExtendedState(MAXIMIZED_BOTH);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lbCodigoProduto;
    private javax.swing.JLabel lbCodigoBarras;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbAplicacao;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbItens;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane tabelaPesquisaProdutos;
    private javax.swing.JScrollPane tabelaProdutos;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtAplicacao;
    // End of variables declaration                   
}
