/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * 
 * @author Ricardo Caldeira
 *
 */
public class PnlPesquisaProduto extends javax.swing.JPanel {

    /**
     * Creates new form PnlPesquisaProduto
     */
    public PnlPesquisaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbtCabecalho = new javax.swing.JLabel();
        pnlDadosPesquisa = new javax.swing.JPanel();
        lbtPesquisaDescricao = new javax.swing.JLabel();
        lbtPesquisaCodigoBarras = new javax.swing.JLabel();
        lbtPesquisaMedida = new javax.swing.JLabel();
        lbtPesquisaAplicacao = new javax.swing.JLabel();
        txtPesquisaCodigoBarras = new javax.swing.JTextField();
        txtPesquisaDescricao = new javax.swing.JTextField();
        txtPesquisaAplicacao = new javax.swing.JTextField();
        txtPesquisaMedida = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        pnlResultadoPesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultadoPesquisa = new javax.swing.JTable();

        lbtCabecalho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbtCabecalho.setForeground(new java.awt.Color(102, 102, 255));
        lbtCabecalho.setText("Formulario de Pesquisa de Produtos");
        lbtCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        pnlDadosPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbtPesquisaDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbtPesquisaDescricao.setText("Descrição");

        lbtPesquisaCodigoBarras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbtPesquisaCodigoBarras.setText("Código de Barras");

        lbtPesquisaMedida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbtPesquisaMedida.setText("Medida");

        lbtPesquisaAplicacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbtPesquisaAplicacao.setText("Aplicação");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lupas_1330_21.jpg"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/domesticos_2141_porta.gif"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPesquisaLayout = new javax.swing.GroupLayout(pnlDadosPesquisa);
        pnlDadosPesquisa.setLayout(pnlDadosPesquisaLayout);
        pnlDadosPesquisaLayout.setHorizontalGroup(
            pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosPesquisaLayout.createSequentialGroup()
                        .addComponent(lbtPesquisaCodigoBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbtPesquisaMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtPesquisaDescricao)
                            .addComponent(lbtPesquisaAplicacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisaAplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtPesquisaDescricao))))
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlDadosPesquisaLayout.setVerticalGroup(
            pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair)
                    .addGroup(pnlDadosPesquisaLayout.createSequentialGroup()
                        .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtPesquisaCodigoBarras)
                            .addComponent(txtPesquisaCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtPesquisaMedida)
                            .addComponent(txtPesquisaMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtPesquisaDescricao)
                            .addComponent(txtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtPesquisaAplicacao))
                .addGap(234, 234, 234))
        );

        tblResultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultadoPesquisa);

        javax.swing.GroupLayout pnlResultadoPesquisaLayout = new javax.swing.GroupLayout(pnlResultadoPesquisa);
        pnlResultadoPesquisa.setLayout(pnlResultadoPesquisaLayout);
        pnlResultadoPesquisaLayout.setHorizontalGroup(
            pnlResultadoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlResultadoPesquisaLayout.setVerticalGroup(
            pnlResultadoPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(lbtCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlResultadoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtCabecalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlResultadoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtCabecalho;
    private javax.swing.JLabel lbtPesquisaAplicacao;
    private javax.swing.JLabel lbtPesquisaCodigoBarras;
    private javax.swing.JLabel lbtPesquisaDescricao;
    private javax.swing.JLabel lbtPesquisaMedida;
    private javax.swing.JPanel pnlDadosPesquisa;
    private javax.swing.JPanel pnlResultadoPesquisa;
    private javax.swing.JTable tblResultadoPesquisa;
    private javax.swing.JTextField txtPesquisaAplicacao;
    private javax.swing.JTextField txtPesquisaCodigoBarras;
    private javax.swing.JTextField txtPesquisaDescricao;
    private javax.swing.JTextField txtPesquisaMedida;
    // End of variables declaration                   
}
