/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author RicardoNote
 */
public class PnlVendasProdutos extends javax.swing.JPanel {

    /**
     * Creates new form PnlVendasProdutos
     */
    public PnlVendasProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbIdProdutos = new javax.swing.JLabel();
        lbIdProdutos1 = new javax.swing.JLabel();
        txtIdProdutos = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbIdProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbIdProdutos.setText("Produto");

        lbIdProdutos1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbIdProdutos1.setText("Descrição");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lbIdProdutos)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(txtIdProdutos, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(lbIdProdutos1)
        					.addGap(18)
        					.addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton1)))
        			.addGap(27))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lbIdProdutos)
        				.addComponent(lbIdProdutos1)
        				.addComponent(txtIdProdutos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1))
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(274, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbIdProdutos;
    private javax.swing.JLabel lbIdProdutos1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdProdutos;
    // End of variables declaration                   
}
